### ISSUE TITLE
Can't run nfcdump. Error message Unknown Text Formatbigmac

### ISSUE THREAD

**Issue by N0ury** [warthog33/nfcdump#1]
Hi
I would like to use 
When I run `adb shell dumpsys nfc | ./nfcdump` I get the error: `Unknown Text Formatbigmac`
Here's attached the file I get when running `adb shell dumpsys nfc > nfcsnoop.log`
[nfcsnoop.log](https://github.com/warthog33/nfcdump/files/14137337/nfcsnoop.log)

Thanks for your help

**Comment by warthog33** [comment]
Hi,

Thanks for your email, will take a look and see if I can fix the issue.

Cheers

**Comment by N0ury** [comment]
Any news?

**Comment by warthog33** [comment]
Please try again. You should get output similar to the following:
$nfcdump % ./nfcdump < nfcsnoop.log | head
inputlen=23298
nfcsnooz_preamble.version=1 nfcsnooz_preamble.last_timestamp_ms=1706861217000047i
Decompressed size=86680
Default log detected len=2329804 00  00 00 00 00  00 Len=4 Delta_Time_ms=0 IsRcvd=0
 20 00 01              NCI_MT_CMD Oid='Core Reset' Len=01 
  01 
04 00  b1 bf 00 00  01 Len=4 Delta_Time_ms=49073 IsRcvd=1
 40 00 01              NCI_MT_RSP Oid='Core Reset' Len=01 
  00 
0c 00  e7 03 00 00  01 Len=12 Delta_Time_ms=999 IsRcvd=1
 60 00 09              NCI_MT_NTF Oid='Core Reset' Len=09 
  02 01 20 04 04 51 12 41 91 
05 00  b2 01 00 00  00 Len=5 Delta_Time_ms=434 IsRcvd=0

**Comment by N0ury** [comment]
@warthog33 Thanks a lot, it works fine now.
I close the issue.
